### ISSUE TITLE
Plugin won't initialize, throws errors

### ISSUE THREAD

**Issue by jtaylorjohnson** [asednev/homebridge-plugin-govee#26]
**Describe The Bug:**
Every time I reboot Homebridge I get errors when it try to start up this plugin. It then never scans for/shows my devices.

**To Reproduce:**
Start homebridge
I have re-installed homebridge, and even raspberry pi os itself 

**Expected behavior:**
Plugin to find and display my govee thermometers

**Logs:**

```
[16/03/2021, 03:05:52] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[16/03/2021, 03:05:57] [HB Supervisor] Restarting Homebridge...
[16/03/2021, 03:05:57] [HB Supervisor] Starting Homebridge with extra flags: -I
[16/03/2021, 03:05:57] [HB Supervisor] Started Homebridge v1.3.3 with PID: 3641
Initializing HAP-NodeJS v0.9.3...
[16/03/2021, 03:05:58] Loaded config.json with 4 accessories and 5 platforms.
[16/03/2021, 03:05:58] Loaded 0 cached accessories from cachedAccessories.
[16/03/2021, 03:05:58] ---
[16/03/2021, 03:05:59] Loaded plugin: homebridge-camera-ffmpeg@3.1.2
[16/03/2021, 03:05:59] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[16/03/2021, 03:05:59] ---
[16/03/2021, 03:05:59] Loaded plugin: homebridge-config-ui-x@4.40.0
[16/03/2021, 03:05:59] Registering platform 'homebridge-config-ui-x.config'
[16/03/2021, 03:05:59] ---
[16/03/2021, 03:05:59] Loaded plugin: homebridge-dummy@0.5.0
[16/03/2021, 03:05:59] Registering accessory 'homebridge-dummy.DummySwitch'
[16/03/2021, 03:05:59] ---
[16/03/2021, 03:05:59] Loaded plugin: homebridge-messenger@0.0.8
[16/03/2021, 03:05:59] Registering accessory 'homebridge-messenger.HomebridgeMessenger'
[16/03/2021, 03:05:59] ---
[16/03/2021, 03:05:59] Loaded plugin: homebridge-nest@4.5.3
[16/03/2021, 03:05:59] Registering platform 'homebridge-nest.Nest'
[16/03/2021, 03:05:59] ---
[16/03/2021, 03:05:59] Loaded plugin: homebridge-plugin-govee@1.0.12
[16/03/2021, 03:05:59] Registering platform 'homebridge-plugin-govee.GoveeHomebridgePlugin'
[16/03/2021, 03:05:59] ---
[16/03/2021, 03:06:00] Loaded plugin: homebridge-ring@9.15.4
[16/03/2021, 03:06:00] Registering platform 'homebridge-ring.Ring'
[16/03/2021, 03:06:00] ---
[16/03/2021, 03:06:00] Loading 5 platforms...
[16/03/2021, 03:06:00] [Config] Initializing config platform...
[16/03/2021, 03:06:00] [Config] Running in Service Mode
[16/03/2021, 03:06:00] [Ring] Initializing Ring platform...
[16/03/2021, 03:06:00] [Ring] Initializing child bridge 0E:BD:D2:B3:8D:00
[16/03/2021, 03:06:00] [Nest] Initializing Nest platform...
[16/03/2021, 03:06:00] [Nest] Initializing child bridge 0E:ED:C4:3E:E2:D9
[16/03/2021, 03:06:00] [Camera FFmpeg] Initializing Camera-ffmpeg platform...
[16/03/2021, 03:06:00] [Camera FFmpeg] Initializing child bridge 0E:1A:D9:82:FA:6C
[16/03/2021, 03:06:00] [Govee] Initializing GoveeHomebridgePlugin platform...
[16/03/2021, 03:06:00] [Govee] Finished initializing platform: Govee
[16/03/2021, 03:06:00] Loading 4 accessories...
[16/03/2021, 03:06:00] [Messenger] Initializing HomebridgeMessenger accessory...
[16/03/2021, 03:06:00] [Messenger] Initializing child bridge 0E:C5:10:F1:DD:94
[16/03/2021, 03:06:00] [Present] Initializing DummySwitch accessory...
[16/03/2021, 03:06:00] [Present] Initializing child bridge 0E:AB:37:4C:1E:AC
[16/03/2021, 03:06:00] [Present] Initializing DummySwitch accessory...
[16/03/2021, 03:06:00] [Present] Initializing child bridge 0E:EB:E0:4E:F5:9A
[16/03/2021, 03:06:00] [Present] Initializing DummySwitch accessory...
[16/03/2021, 03:06:00] [Present] Initializing child bridge 0E:DF:32:A6:D4:1C
Preparing Advertiser for 'Homebridge 1234 567' using bonjour-hap backend!
Setup Payload:
X-HM://0024LMNIH2CE9
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ ABC-12-123 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge ABCD 1234' using bonjour-hap backend!
[16/03/2021, 03:06:01] Homebridge v1.3.3 (Homebridge 8C5D) is running on port 51627.
(node:3641) UnhandledPromiseRejectionWarning: Error: ENODEV, No such device
    at Hci.init (/usr/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/hci.js:114:35)
    at NobleBindings.init (/usr/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:82:13)
    at Noble.startScanning (/usr/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/noble.js:132:20)
    at /usr/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/noble.js:142:44
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at internal/util.js:296:12
    at Noble.startScanningAsync (/usr/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/noble.js:142:99)
    at Object.exports.startDiscovery (/usr/lib/node_modules/homebridge-plugin-govee/node_modules/govee-bt-client/dist/index.js:83:27)
    at GoveeHomebridgePlatform.discoverDevices (/usr/lib/node_modules/homebridge-plugin-govee/src/platform.ts:78:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3641) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3641) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Initializing HAP-NodeJS v0.9.3...
[16/03/2021, 03:06:02] [Present] Launched child bridge with PID 3684
```

Then it just continues as normal from that point.

**Plugin Config:**

```json
},
        {
            "name": "Govee",
            "batteryThreshold": 25,
            "debug": false,
            "humidityOffset": 0,
            "platform": "GoveeHomebridgePlugin"
        }
    ]
}
```

**Screenshots:**
n/a

**Environment:**

* **Plugin Version**:1.0.12
* **Homebridge Version**: 1.3.3
* **Node.js Version**: 14.16.0
* **NPM Version**: 6.14.11
* **Operating System**: Raspbian

**Comment by asednev** [comment]
@jtaylorjohnson `Error: ENODEV, No such device` indicates that `cci-socket` library which is used by [noble](https://github.com/abandonware/noble) can't find a compatible bluetooth module. I suggest you look into [troubleshooting steps](https://github.com/abandonware/noble#advanced-usage) for noble or raise an issue for that package.
