### ISSUE TITLE
Unable to run plugin through docker

### ISSUE THREAD

**Issue by dvdcmrn** [asednev/homebridge-plugin-govee#29]
**Describe Your Problem:**
I run Homebridge through Docker on a Raspberry Pi 4B running Ubuntu. Everything is up to date.
After installing **homebridge-plugin-govee v1.0.12** through the web-interface the logs show following issues

**Logs:**

```
[3/30/2021, 3:38:45 PM] Homebridge v1.3.4 (Homebridge) is running on port 51735.
(node:1617) UnhandledPromiseRejectionWarning: Error: ENODEV, No such device
    at Hci.init (/homebridge/node_modules/govee-bt-client/node_modules/@abandonware/noble/lib/hci-socket/hci.js:114:35)
    at NobleBindings.init (/homebridge/node_modules/govee-bt-client/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:82:13)
    at Noble.startScanning (/homebridge/node_modules/govee-bt-client/node_modules/@abandonware/noble/lib/noble.js:132:20)
    at /homebridge/node_modules/govee-bt-client/node_modules/@abandonware/noble/lib/noble.js:142:44
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at internal/util.js:296:12
    at Noble.startScanningAsync (/homebridge/node_modules/govee-bt-client/node_modules/@abandonware/noble/lib/noble.js:142:99)
    at Object.exports.startDiscovery (/homebridge/node_modules/govee-bt-client/dist/index.js:83:27)
    at GoveeHomebridgePlatform.discoverDevices (/homebridge/node_modules/homebridge-plugin-govee/src/platform.ts:78:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1617) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1617) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[3/30/2021, 3:38:45 PM] [BroadlinkRM] [INFO] ...
```

**Plugin Config:**

```json
{
  "name": "Govee",
  "batteryThreshold": 25,
  "debug": false,
  "humidityOffset": 0,
  "platform": "GoveeHomebridgePlugin"
}
```

**Environment:**

* **Plugin Version**: 1.0.12
* **Homebridge Version**: 1.3.4
* **Node.js Version**: 14.16.0
* **NPM Version**: 7.7.5
* **Operating System**: Docker

**Comment by dvdcmrn** [comment]
Same thing happens when i install it directly on ubuntu

```
(node:3654) UnhandledPromiseRejectionWarning: Error: ENODEV, No such device
    at Hci.init (/usr/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/hci.js:114:35)
    at NobleBindings.init (/usr/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:82:13)
    at Noble.startScanning (/usr/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/noble.js:132:20)
    at /usr/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/noble.js:142:44
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at internal/util.js:296:12
    at Noble.startScanningAsync (/usr/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/noble.js:142:99)
    at Object.exports.startDiscovery (/usr/lib/node_modules/homebridge-plugin-govee/node_modules/govee-bt-client/dist/index.js:83:27)
    at GoveeHomebridgePlatform.discoverDevices (/usr/lib/node_modules/homebridge-plugin-govee/src/platform.ts:78:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3654) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3654) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by asednev** [comment]
@dvdcmrn there is no specific limitation in the plugin. I recommend taking a look at instructions for [noble library](https://github.com/abandonware/noble#docker) for docker support.
