### ISSUE TITLE
Incompatible with other bluetooth Homebridge plugins

### ISSUE THREAD

**Issue by apexad** [asednev/homebridge-plugin-govee#5]
**Describe The Bug:**
Incompatible with other plugins using noble, like: https://github.com/SwitchBot/homebridge-switchbot-ble/
What happens is the switch bot activates and turns the switch, but then this plugin is causing homebdige to crash.

**To Reproduce:**
Install a Switch Bot (or any other bluetooth device that has a Homebridge plugin), add the Homebridge plugin, configure the device.  Click the switch to make the switch bot go (or whatever for your bluetooth device) and this is when Homebridge crashes with the following error log below.

**Expected behavior:**
No crash from Homebridge. Seems like this or `govee-bt-client` are looking at requests it should be be and causing a crash.

**Logs:**

```
noble: unknown peripheral <MAC OF SWITCHBOT> handle notify!
[08/11/2020, 21:35:59] TypeError: Cannot set property 'mtu' of undefined
    at Noble.onMtu (/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/noble.js:564:18)
    at NobleBindings.emit (events.js:315:20)
    at NobleBindings.onMtu (/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:277:8)
    at Gatt.emit (events.js:315:20)
    at Object.callback (/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:329:10)
    at Gatt.onAclStreamData (/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:133:26)
    at AclStream.emit (events.js:327:22)
    at AclStream.push (/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/acl-stream.js:33:10)
    at NobleBindings.onAclDataPkt (/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:288:15)
    at Hci.emit (events.js:315:20)
    at Hci.onSocketData (/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/hci.js:501:14)
    at BluetoothHciSocket.emit (events.js:315:20)
```

**Plugin Config:**

```json
        {
            "name": "Govee",
            "batteryThreshold": 25,
            "debug": false,
            "platform": "GoveeHomebridgePlugin"
        },
        {
            "platform": "SwitchBotPlatform",
            "name": "SwitchBotPlatform",
            "devices": [
                {
                    "type": "bot",
                    "name": "Switch Bot Switch 1",
                    "bleMac": "<MAC>"
                }
            ]
        }
```

**Screenshots:**
None needed

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 1.1.6
* **Node.js Version**: 14.15
* **NPM Version**: 6.14.8
* **Operating System**: Raspbian / hb-service

**Comment by asednev** [comment]
@apexad sorry for slow response, my plate has been full at work. It seems like an issue with noble, potentially different, incompatible, versions of noble used by two plugins. I will investigate when time permits.

**Comment by apexad** [comment]
If it is version of noble, it is `1.9.2-9` in your code versus `1.9.2-10` used by switchbot.

**Comment by asednev** [comment]
I was unable to reproduce this crash on my system. I will update noble dependency to match another plugin for next release; maybe that will help.

**Comment by asednev** [comment]
@apexad [1.0.5](https://www.npmjs.com/package/homebridge-plugin-govee/v/1.0.5) updates noble to `1.9.2-10`, this might solve your issue.
