### ISSUE TITLE
Plug-in keeps rebooting over and over

### ISSUE THREAD

**Issue by MalachiteXD** [asednev/homebridge-plugin-govee#54]
**Describe Your Problem:**
Plug-in worked just fine up until a few versions ago, (2) I believe. Now I get the below error, even after following the Bluetooth instructions
(Also get same error if not in a child bridge)

**Logs:**

```

[08/01/2022, 16:58:53] [Govee] Launched child bridge with PID 15258
[08/01/2022, 16:58:54] Registering platform 'homebridge-plugin-govee.GoveeHomebridgePlugin'
[08/01/2022, 16:58:54] [Govee] Loaded homebridge-plugin-govee v1.1.4 child bridge successfully
[08/01/2022, 16:58:54] [Govee] Finished initializing platform: Govee
[08/01/2022, 16:58:54] Homebridge v1.3.9 (HAP v0.9.8) (Govee) is running on port 49007.

/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/hci.js:121
      this._socket.bindRaw(this._deviceId);
                   ^
Error: ENODEV, No such device
    at Hci.init (/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/hci.js:121:20)
    at NobleBindings.init (/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:93:13)
    at Noble.startScanning (/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/noble.js:145:20)
    at /usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/noble.js:155:44
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at node:internal/util:346:12
    at Noble.startScanningAsync (/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/noble.js:155:99)
    at startDiscovery (/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/govee-bt-client/dist/index.js:84:27)
    at GoveeHomebridgePlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-plugin-govee/src/platform.ts:88:24)
[08/01/2022, 16:58:54] [Govee] Child bridge process ended
[08/01/2022, 16:58:54] [Govee] Process Ended. Code: 1, Signal: null
[08/01/2022, 16:59:01] [Govee] Restarting Process...

```

**Plugin Config:**

```json

{
            "name": "Govee",
            "batteryThreshold": 25,
            "debug": false,
            "humidityOffset": 0,
            "platform": "GoveeHomebridgePlugin",
            "_bridge": {
                "username": "0E:D5:D9:F9:7D:BE",
                "port": 49007
            }

```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.1.4
* **Homebridge Version**: 1.3.9
* **Node.js Version**: 16.13.1
* **NPM Version**: 8.3.0
* **Operating System**: Raspbian GNU

**Comment by mpreissner** [comment]
Also having this problem, but it started after updating node.js from 14.x to 16.x.  Reinstalled the plugin so it would recompile against updated node.js, and these errors are what resulted.

**Comment by asednev** [comment]
I recommend downgrading to node 14, removing `node_modules`, and reinstalling the dependencies.
