### ISSUE TITLE
Govee Plugin fails to start after migrating to new device with EAFNOSUPPORT, Address family not supported by protocol

### ISSUE THREAD

**Issue by 1ne** [asednev/homebridge-plugin-govee#68]
I used backup and restore functionality to switch to a new Raspberry Pi. After the migration this plugin failed to start with the error below. I've installed noble and other bluetooth dependencies.

Please see the error log below. 

```
[7/20/2022, 7:30:57 PM] ====================
[7/20/2022, 7:30:57 PM] ERROR LOADING PLUGIN homebridge-plugin-govee:
[7/20/2022, 7:30:57 PM] Error: EAFNOSUPPORT, Address family not supported by protocol
    at new Hci (/var/lib/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/hci.js:80:18)
    at new NobleBindings (/var/lib/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:25:15)
    at module.exports (/var/lib/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/lib/resolve-bindings.js:13:12)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/noble/index.js:2:51)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-plugin-govee/node_modules/govee-bt-client/dist/index.js:17:33)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[7/20/2022, 7:30:57 PM] ====================
```

Environment:
- Plugin Version: 1.1.6
- Homebridge Version: 1.5.0
- Node.js Version: 16.16.0
- NPM Version: 8.13.2
- Operating System: DietPi 8.6.1 on Pi 3 B+

**Comment by 1ne** [comment]
I used the raspberry pi image for homebridge and that solved the issue for me.
